server:
  port: 9001
spring:
  application:
    name: leadnews-admin
  kafka:
    bootstrap-servers: ${kafka.servers}
    consumer:
      group-id: ${spring.application.name}-kafka-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server}
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.admin.pojos

#图片访问ip
fdfs.url: ${fdfs.url}
xxljob:
  admin:
    addresses: ${xxljob.admin.addresses}
  executor:
    appname: ${xxljob.admin.appname}
    port: ${xxljob.admin.port}
#取消对elastsearch的健康检查
management:
  health:
    elasticsearch:
      enabled: false
#自定义elasticsearch连接配置
elasticsearch:
  host: ${elasticsearch.host}
  port: ${elasticsearch.port}